### ISSUE TITLE
Extra warnings for deleting jobs

### ISSUE THREAD

**Issue by jweede** [nerdling/jenkins-job-manager#6]
It's a little too easy to delete jobs and wipe out build history. 
We should prompt for extra confirmation when a changeset calls for deleting jobs.

 - prompt for extra confirmation (force typing out "yes" like TF)
 - list jobs to delete
 - look scary with colors

**Comment by nerdling** [comment]
If delete is not considered normal operation for this tooling, then we shouldn't even allow deletions by default.

Perhaps this should instead be a flag that even allows deletes?

**Comment by jweede** [comment]
That sounds better. We could disable deletes normally, and only allow with a flag like `--allow-delete`
